### PR TITLE
Vlad script1

### PR DESCRIPTION
**Pull request by VladVestem**
bonus 1 & 2

### CODE REVIEW

**Review by nbiro — COMMENTED** [review]
looks pretty good, can you remove code duplication?

**Comment by VladVestem** [comment]
> looks pretty good, can you remove code duplication?

Should I move duplicate code outside the two functions, or make new functions with the duplicate code and use it inside the existing two functions?

**Comment by nbiro** [comment]
> > looks pretty good, can you remove code duplication?
> 
> Should I move duplicate code outside the two functions, or make new functions with the duplicate code and use it inside the existing two functions?

either way works.

**Review by nbiro — APPROVED** [review]
👌

**Review by nbiro — APPROVED** [review]

**Pull request merged**
